point = 180001;

Left_singular_value =[y_sys_icl_left_11(point),y_sys_icl_left_12(point),y_sys_icl_left_13(point);...
                      y_sys_icl_left_21(point),y_sys_icl_left_22(point),y_sys_icl_left_23(point);...
                      y_sys_icl_left_31(point),y_sys_icl_left_31(point),y_sys_icl_left_33(point)] ;
singular_value =[y_sys_icl_11(point),y_sys_icl_12(point),y_sys_icl_13(point),y_sys_icl_14(point),y_sys_icl_15(point),y_sys_icl_16(point),y_sys_icl_17(point),y_sys_icl_18(point),y_sys_icl_19(point);...
                y_sys_icl_21(point),y_sys_icl_22(point),y_sys_icl_23(point),y_sys_icl_24(point),y_sys_icl_25(point),y_sys_icl_26(point),y_sys_icl_27(point),y_sys_icl_28(point),y_sys_icl_29(point);...
                y_sys_icl_31(point),y_sys_icl_32(point),y_sys_icl_33(point),y_sys_icl_34(point),y_sys_icl_35(point),y_sys_icl_36(point),y_sys_icl_37(point),y_sys_icl_38(point),y_sys_icl_39(point)] ;
Right_singular_value =[y_sys_icl_right_11(point),y_sys_icl_right_12(point),y_sys_icl_right_13(point),y_sys_icl_right_14(point),y_sys_icl_right_15(point),y_sys_icl_right_16(point),y_sys_icl_right_17(point),y_sys_icl_right_18(point),y_sys_icl_right_19(point);...
                      y_sys_icl_right_21(point),y_sys_icl_right_22(point),y_sys_icl_right_23(point),y_sys_icl_right_24(point),y_sys_icl_right_25(point),y_sys_icl_right_26(point),y_sys_icl_right_27(point),y_sys_icl_right_28(point),y_sys_icl_right_29(point);...
                        y_sys_icl_right_31(point),y_sys_icl_right_32(point),y_sys_icl_right_33(point),y_sys_icl_right_34(point),y_sys_icl_right_35(point),y_sys_icl_right_36(point),y_sys_icl_right_37(point),y_sys_icl_right_38(point),y_sys_icl_right_39(point);...
                        y_sys_icl_right_41(point),y_sys_icl_right_42(point),y_sys_icl_right_43(point),y_sys_icl_right_44(point),y_sys_icl_right_45(point),y_sys_icl_right_46(point),y_sys_icl_right_47(point),y_sys_icl_right_48(point),y_sys_icl_right_49(point);...
                        y_sys_icl_right_51(point),y_sys_icl_right_52(point),y_sys_icl_right_53(point),y_sys_icl_right_54(point),y_sys_icl_right_55(point),y_sys_icl_right_56(point),y_sys_icl_right_57(point),y_sys_icl_right_58(point),y_sys_icl_right_59(point);...
                       y_sys_icl_right_61(point),y_sys_icl_right_62(point),y_sys_icl_right_63(point),y_sys_icl_right_64(point),y_sys_icl_right_65(point),y_sys_icl_right_66(point),y_sys_icl_right_67(point),y_sys_icl_right_68(point),y_sys_icl_right_69(point);...
                        y_sys_icl_right_71(point),y_sys_icl_right_72(point),y_sys_icl_right_73(point),y_sys_icl_right_74(point),y_sys_icl_right_75(point),y_sys_icl_right_76(point),y_sys_icl_right_77(point),y_sys_icl_right_78(point),y_sys_icl_right_79(point);...
                        y_sys_icl_right_81(point),y_sys_icl_right_82(point),y_sys_icl_right_83(point),y_sys_icl_right_84(point),y_sys_icl_right_85(point),y_sys_icl_right_86(point),y_sys_icl_right_87(point),y_sys_icl_right_88(point),y_sys_icl_right_89(point);...
                        y_sys_icl_right_91(point),y_sys_icl_right_92(point),y_sys_icl_right_93(point),y_sys_icl_right_94(point),y_sys_icl_right_95(point),y_sys_icl_right_96(point),y_sys_icl_right_97(point),y_sys_icl_right_98(point),y_sys_icl_right_99(point)] ;
